name: A workflow for my Hello World file
on: [push, pull_request]
jobs:
  x64_job:
    name: Build on x64 linux distro
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
      - name: Show environment
        run: |
          uname -o
          uname -m
  arm_job:
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}
    runs-on: ubuntu-latest
    # Run steps on a matrix of 3 arch/distro combinations
    strategy:
      matrix:
        include:
          - arch: armv7
            distro: ubuntu18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: emulate arm environment
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}

          # Not required, but speeds up builds
          githubToken: ${{ github.token }}
          # Create an artifacts directory
          setup: |
            ls
            mkdir -p "${PWD}/artifacts"
          # The shell to run commands with in the container
          shell: /bin/sh
          install: |
            case "${{ matrix.distro }}" in
              ubuntu*|jessie|stretch|buster)
                apt-get update -q -y
                apt-get install -q -y git
                apt-get install -q -y wget
                ;;
              fedora*)
                dnf -y update
                dnf -y install git which
                ;;
              alpine*)
                apk update
                apk add git
                ;;
            esac
          run: |
            export GOARM=7
            export GOARCH=arm
            git status
            wget https://golang.org/dl/go1.15.linux-armv6l.tar.gz
            tar -C /usr/local -xzf go1.15.linux-armv6l.tar.gz
            export PATH=$PATH:/usr/local/go/bin
            
            go version
            uname -o
            uname -m
