name: Status Check
on: [push, pull_request]
jobs:
  x64_job:
    name: Build on x64 linux distro
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
      - name: Show environment
        run: |
          uname -o
          uname -m
      - name: Sleep
        run: |
          curl --header "Content-Type: application/json" \
                --request POST \
                --data '{"org":"zhihanz","repo":"hello-github-actions", "pr": "test", "commitSHA": "${{github.event.pull_request.head.sha}}", "run_id": "${{github.run_id}}"}' \
                https://manitoba-underlying-con-slot.trycloudflare.com/status || exit 1
          curl --header "Content-Type: application/json" \
                --request POST \
                --data '{"org":"zhihanz","repo":"hello-github-actions", "pr": "test", "commitSHA": "${{github.event.pull_request.head.sha}}", "run_id": "${{github.run_id}}"}' \
                https://manitoba-underlying-con-slot.trycloudflare.com/status || exit 1