name: Status Check
on: [push, pull_request]
jobs:
  x64_job:
    name: Build on x64 linux distro
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
      - name: Show environment
        run: |
          uname -o
          uname -m
      - name: Sleep
        run: |
          echo https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
          sleep 60s
          echo https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}

